services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  lambda-local:
    build:
      context: ./app
    container_name: lambda_local
    depends_on:
      - postgis
    env_file:
      - .env
    volumes:
      - ./app/geojson_sample:/app/geojson_sample
    command: [ "python", "run_local.py" ]
